### ISSUE TITLE
Review the documentation before registering the package 

### ISSUE THREAD

**Issue by himanshugupta1009** [CU-ADCL/HybridAStar.jl#1]
Let me know of the changes that you think are needed. Thanks!

@zsunberg

**Comment by zsunberg** [comment]
- [x] Add docstrings with this format: https://docs.julialang.org/en/v1/manual/documentation/

- [x] then copy them into the README

**Comment by zsunberg** [comment]
In the github repo settings, 

- [x] 1) Transfer the repo to the CU-ADCL org

2) Then register with this: https://julialang.org/contribute/developing_package/#step_5_register_your_package

**Comment by zsunberg** [comment]
- [x] Before registering , you have to provide compat entries in the Project.toml for all dependencies https://pkgdocs.julialang.org/v1/compatibility/

**Comment by zsunberg** [comment]
- [x] Add tests https://julialang.org/contribute/developing_package/#step_4_test_your_package
